# Generated by Django 2.0.1 on 2018-03-03 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ga', '0002_auto_20180303_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='program',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
