# Generated by Django 2.0.1 on 2018-03-04 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ga', '0003_auto_20180303_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ga.Program'),
        ),
    ]
