# Generated by Django 2.0.1 on 2018-03-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ga', '0003_auto_20180312_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentmethod',
            name='current_flag',
            field=models.BooleanField(default=True),
        ),
    ]
