# Generated by Django 2.0.1 on 2018-03-14 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ga', '0004_assessmentmethod_current_flag'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='indicator',
            unique_together={('code',)},
        ),
    ]
