# Generated by Django 2.0.1 on 2018-03-04 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ga', '0004_auto_20180304_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ga.Program'),
        ),
    ]
