# Generated by Django 2.0.1 on 2018-03-04 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ga', '0005_auto_20180304_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentmethod',
            name='current_flag',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='current_flag',
        ),
        migrations.RemoveField(
            model_name='course',
            name='current_flag',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='current_flag',
        ),
        migrations.RemoveField(
            model_name='program',
            name='current_flag',
        ),
    ]
