# Generated by Django 2.0.1 on 2018-03-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ga', '0005_auto_20180314_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentmethod',
            name='method',
            field=models.CharField(default='nil', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together={('code',)},
        ),
    ]
