# Generated by Django 2.0.1 on 2018-03-05 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ga', '0006_auto_20180304_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentmethod',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ga.Indicator'),
        ),
    ]
