# Generated by Django 2.0.1 on 2018-03-15 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ga', '0006_auto_20180315_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessmentmethod',
            old_name='method',
            new_name='assessment_medium',
        ),
    ]
