# Generated by Django 2.0.1 on 2018-03-05 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ga', '0007_auto_20180305_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentmethod',
            name='programs',
        ),
        migrations.AddField(
            model_name='indicator',
            name='program',
            field=models.OneToOneField(default='temp', on_delete=django.db.models.deletion.PROTECT, to='ga.Program'),
            preserve_default=False,
        ),
    ]
