# Generated by Django 2.0.1 on 2018-03-05 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ga', '0008_auto_20180305_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='programs',
            field=models.ManyToManyField(to='ga.Program'),
        ),
        migrations.AlterField(
            model_name='assessmentmethod',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ga.Indicator'),
        ),
    ]
