# Generated by Django 2.0.1 on 2018-03-05 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ga', '0010_remove_indicator_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentmethod',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ga.Indicator'),
        ),
    ]
