# Generated by Django 2.0.1 on 2018-03-06 16:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ga', '0011_auto_20180305_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='current_flag',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='assessment',
            unique_together={('semester', 'teacher', 'assessmentMethod', 'program')},
        ),
    ]
