# Generated by Django 2.0.1 on 2018-03-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ga', '0012_auto_20180306_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
