# Generated by Django 2.0.1 on 2018-03-09 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ga', '0013_auto_20180306_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='current_flag',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ga.Program'),
        ),
        migrations.AlterField(
            model_name='assessmentmethod',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ga.Indicator'),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
