# Generated by Django 2.0.1 on 2018-03-09 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ga', '0014_auto_20180309_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='current_flag',
        ),
        migrations.AddField(
            model_name='attribute',
            name='current_flag',
            field=models.BooleanField(default=True),
        ),
    ]
