# Generated by Django 2.0.1 on 2018-03-09 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ga', '0015_auto_20180309_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='current_flag',
        ),
    ]
