# Generated by Django 2.0.1 on 2018-03-12 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ga', '0016_remove_attribute_current_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='current_flag',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='current_flag',
            field=models.BooleanField(default=True),
        ),
    ]
