# Generated by Django 2.0.1 on 2018-01-19 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expectation4', models.CharField(max_length=1000)),
                ('expectation3', models.CharField(max_length=1000)),
                ('expectation2', models.CharField(max_length=1000)),
                ('expectation1', models.CharField(max_length=1000)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('current_flag', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('current_flag', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('current_flag', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Course_AssessmentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('numOf4', models.PositiveSmallIntegerField()),
                ('numOf3', models.PositiveSmallIntegerField()),
                ('numOf2', models.PositiveSmallIntegerField()),
                ('numOf1', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('current_flag', models.BooleanField()),
                ('AssesessmentMethodID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.AssessmentMethod')),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('current_flag', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('expectation4', models.CharField(max_length=1000)),
                ('expectation3', models.CharField(max_length=1000)),
                ('expectation2', models.CharField(max_length=1000)),
                ('expectation1', models.CharField(max_length=1000)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('current_flag', models.BooleanField()),
                ('attributeID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Attribute')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('current_flag', models.BooleanField()),
                ('departmentID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Utilized',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('current_flag', models.BooleanField()),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Course')),
                ('indicatorID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Indicator')),
            ],
        ),
        migrations.AddField(
            model_name='indicator',
            name='utilizedBy',
            field=models.ManyToManyField(through='main.Utilized', to='main.Course'),
        ),
        migrations.AddField(
            model_name='course',
            name='departmentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Department'),
        ),
        migrations.AddField(
            model_name='course',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentmethod',
            name='course',
            field=models.ManyToManyField(through='main.Course_AssessmentMethod', to='main.Course'),
        ),
        migrations.AddField(
            model_name='assessmentmethod',
            name='indicatorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Indicator'),
        ),
    ]
