# Generated by Django 2.0.1 on 2018-01-19 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Introduced',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('current_flag', models.BooleanField()),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Course')),
            ],
        ),
        migrations.AlterField(
            model_name='indicator',
            name='utilizedBy',
            field=models.ManyToManyField(related_name='utilizedBy', through='main.Utilized', to='main.Course'),
        ),
        migrations.AddField(
            model_name='introduced',
            name='indicatorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Indicator'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='introducedBy',
            field=models.ManyToManyField(related_name='introducedBy', through='main.Introduced', to='main.Course'),
        ),
    ]
