# Generated by Django 2.0.1 on 2018-01-19 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180119_0155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taught',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('current_flag', models.BooleanField()),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Course')),
            ],
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='introducedBy',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='utilizedBy',
        ),
        migrations.AddField(
            model_name='indicator',
            name='introducedIn',
            field=models.ManyToManyField(related_name='introducedIn', through='main.Introduced', to='main.Course'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='utilizedIn',
            field=models.ManyToManyField(related_name='utilizedIn', through='main.Utilized', to='main.Course'),
        ),
        migrations.AddField(
            model_name='taught',
            name='indicatorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Indicator'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='taughtIn',
            field=models.ManyToManyField(related_name='taughtIn', through='main.Taught', to='main.Course'),
        ),
    ]
