# Generated by Django 2.0.1 on 2018-03-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='email',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('object_line', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=2000)),
            ],
        ),
    ]
