# Generated by Django 2.0.1 on 2018-03-01 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automated_email', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='email',
        ),
    ]
